version: "3.3"
services:
  backend:
    build: ./server
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - upload:/upload
    environment:
      DATABASE_CONNECTION: mongodb://db/grap
  db:
    image: mongo:4.0-xenial
    ports:
      - 2717:27017
    restart: unless-stopped
    volumes:
      - phone:/data/db
  web:
    build: ./admin
    ports:
      - 3055:80
    restart: unless-stopped
    volumes:
      - "./admin:/app"
      - "/app/node_modules"
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true


  web1:
    build: ./graborders
    ports:
      - 8081:80
    restart: unless-stopped
    volumes:
      - "./graborders:/app"
      - "/app/node_modules"
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./graborders:/app"
      - "./nginx.conf:/etc/nginx/nginx.conf"
    # depends_on:
    #   - web1
    restart: unless-stopped

volumes:
  phone:
  upload:
